### ISSUE TITLE
Not working on 1.0.2

### ISSUE THREAD

**Issue by favadi** [Graylog2/graylog-plugin-alarmcallback-jabber#3]
I have the exactly error as @pdepaepe in #1  but with graylog 1.0.2. I create new task because #1 is closed.

**Comment by dennisoelkers** [comment]
How did you install the plugin?

**Comment by favadi** [comment]
I just install maven, run `mvn jdeb:jdeb` and install it in the graylog-server machine.

**Comment by favadi** [comment]
I test one more time and realize that it works with normal recipient but not chat room.
This error shows up in log when I try to set recipient field to a chat room.

```
Jun 12 09:33:58 integration-general-local WARN: smack.XMPPConnection  Connection closed with error
Jun 12 09:33:58 integration-general-local stream: error (conflict) text: Replaced by new connection
Jun 12 09:33:58 integration-general-local     at org.jivesoftware.smack.tcp.PacketReader.parsePackets(PacketReader.java:226)
Jun 12 09:33:58 integration-general-local     at org.jivesoftware.smack.tcp.PacketReader.access$000(PacketReader.java:47)
Jun 12 09:33:58 integration-general-local     at org.jivesoftware.smack.tcp.PacketReader$1.run(PacketReader.java:81)
```

So, is sent alerts to chat room supported?

**Comment by favadi** [comment]
Since the title is misleading. I close this issue.
